import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const axiforma = localFont({
  src: [
    {
      path: "../public/fonts/Axiforma/Axiforma_Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Axiforma/Axiforma_Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts//Axiforma/Axiforma_Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-axiforma",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${axiforma.variable} antialiased`}>{children}</body>
    </html>
  );
}
